describe('Customer login',function(){
    it('Customer login page ',function(){
        cy.viewport(1920,1080)
        cy.visit('https://members-qa.coyni.com')
        cy.wait(1000)
        cy.get('#Email').type('ram@ideyalabs.com')
        cy.wait(2000)
        cy.get('#Password').type('Admin@123')
        cy.get('[type=submit]').click()
    })
     //if user enter phone verification
     it('entered phone verification',function(){
        cy.viewport(1920,1080)
    cy.wait(3000)
     cy.get('.VerificationInput_verification_input_wrapper__o8Que > .relative > :nth-child(1)').type('1')
           cy.get('.relative > :nth-child(2)').type('23456')
     })
    it('enter two step authentication',function(){
        cy.viewport(1920,1080)
        cy.wait(1000)
       cy.get('button[style="display: block;"]').click()
        cy.get('.verification-input  ').eq(0).type('1')
        cy.get('.verification-input  ').eq(1).type('2')
        cy.get('.verification-input  ').eq(2).type('3')
        cy.get('.verification-input  ').eq(3).type('4')
        cy.get('.verification-input  ').eq(4).type('5')
        cy.get('.verification-input  ').eq(5).type('6').click()
    })
    it('click on verify your identity',function(){
        cy.viewport(1920,1080)
        cy.wait(2000)
        cy.get('button[style="display: block;"]').click()
        cy.get('#mailing-address-line-1').type('Andhra preadesh')
        cy.get('[for="mailing-address-line-2"]').type('secdrabad')
        cy.get('#city').type('Hyd')
        cy.get('#zipcode').type('87654')
        cy.contains('Date of Birth').type('10 / 10 / 1999')
        cy.get('[for="social-security-no"]').type('1234')
        cy.get('#radio1').click()
    })
})