describe('Login for admin portal', function () {
    it('Login of admin', function () {
        cy.viewport(1920, 1080)
        cy.wait(2000)
        // cy.visit('https://admin-qa.coyni.com/login')
        cy.visit(Cypress.env(Cypress.env("envurl")))
        cy.wait(6000)
        cy.title().should("contain", Cypress.env("titlekeyword"))
    })

    it('Enter email and password and click on next', function () {
        cy.viewport(1920, 1080)
        cy.wait(2000)
        cy.get('#Email').type('swathim@ideyalabs.com')
        cy.get('#Password').type('Admin@123')
        cy.contains('Next').click()
    })
    it('Enter Two step authentication', function () {
        cy.viewport(1920, 1080)
        cy.wait(2000)
        cy.get('.verification-input  ').eq(0).type('1')
        cy.get('.verification-input  ').eq(1).type('2')
        cy.get('.verification-input  ').eq(2).type('3')
        cy.get('.verification-input  ').eq(3).type('4')
        cy.get('.verification-input  ').eq(4).type('5')
        cy.get('.verification-input  ').eq(5).type('6')
    })
    it('Admin able to view their details and change the password', function () {
        cy.viewport(1920, 1080)
        cy.wait(2000)
        cy.get('.down-arrow').click()
        cy.contains('User Details').click()
        cy.wait(2000)
        cy.contains('Change Password').click()
        cy.wait(5000)
        cy.get('.verification-input  ').eq(0).type('1')
        cy.get('.verification-input  ').eq(1).type('2')
        cy.get('.verification-input  ').eq(2).type('3')
        cy.get('.verification-input  ').eq(3).type('4')
        cy.get('.verification-input  ').eq(4).type('5')
        cy.get('.verification-input  ').eq(5).type('6')
        cy.wait(3000)
        cy.contains('Current Password').type('Admin@1234')
        cy.get('#NewPassword').type('Admin@123')
        cy.get('[for="ConfirmNewPassword"]').type('Admin@123')
        cy.contains('Save').click()
    })
})